### ISSUE TITLE
Dependency on old chai

### ISSUE THREAD

**Issue by rissem** [practicalmeteor/meteor-loglevel#4]
Running into this when I try to point mike:mocha to the latest `practicalmeteor:chai`

```
error: Conflict: Constraint practicalmeteor:chai@1.9.2_3 is not satisfied by practicalmeteor:chai 2.1.0_1.
   Constraints on package "practicalmeteor:chai":
   * practicalmeteor:chai@2.1.0_1 <- mike:mocha 0.6.3
   * practicalmeteor:chai@1.9.2_3 <- practicalmeteor:loglevel 1.2.0_1 <- sanjo:long-running-child-process 1.1.2 <- velocity:core 0.7.1 <- mike:mocha 0.6.3
```

It seems very strange considering you don't specify a version in the `package.js` file. Maybe pointing to the latest version of chai (`api.use(['practicalmeteor:chai@2.1.0_1'], ["client", "server"]);`) would fix it. Or maybe the `.versions` file needs to be updated? Let me know if I can be of any help.

**Comment by rbabayoff** [comment]
Mike, just realized it's you. Did you try and set the version of chai in your mocha package?

Also, repeating what I said in pr, try clearing the meteor cache (even though it will probably not work) by re-installing meteor and `meteor reset` in your app. Also maybe `meteor update`?

**Comment by rbabayoff** [comment]
I think I fixed it. Use 1.2.0_2 to verify and let me know.

**Comment by rissem** [comment]
That worked! Thanks @rbabayoff
